window_size:
  width: 1200
  height: 700

log_config:
  log_dir: Log
  log_level: info

author_info:
  author_name: ww
  author_email: 000000@qq.com

io_panel_config:
  default_output: Hello World!
  port_input_placeholder: "未收到任何数据..."
  user_input_placeholder: "未发出任何数据..."

port_panel_config:
  baud_rate_default_vec: [1200, 2400, 4800, 9600, 19200, 38400, 57600, 74800, 115200, 230400, 460800, 921600, 1000000, 1152000, 1500000, 2000000, 2500000, 3000000, 3500000, 4000000]
  default_baud_rate: 115200
  port_update_interval: 1
  read_timeout: 10

common_config:
  font_family: Consolas
  font_size: 14
  default_border_color: 0xFFFFFF
  focus_border_color: 0x8A2BE2
  encoding: Utf8
  decoding: Utf8
  max_lines: 5000
  auto_tx_append_item: \n
