[package]
name = "ww-ui"
version = "0.2.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
gpui = {workspace = true}
gpui_platform = {workspace = true}
gpui-component = {workspace = true}
gpui-component-assets = {workspace = true}
config = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
thiserror = {workspace = true}
anyhow = {workspace = true}
tokio = {workspace = true, features = ["full"]}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
tracing-appender = {workspace = true}
ww-protocol = {path = "../ww-protocol"}
encoding_rs = {workspace = true}
jiff = {workspace = true}
image = {workspace = true}
